### ISSUE TITLE
Clickhouse error

### ISSUE THREAD

**Issue by rez1dent3** [JetBrains/dekaf#10]
Build #PS-182.4505.42, built on September 27, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.10-arch1-1-ARCH

Driver: Clickhouse
Version: 0.1.40

![_2018-10-02_21-08-47](https://user-images.githubusercontent.com/5111255/46368213-4dec8c00-c688-11e8-815f-6beba2b07f77.png)

**Comment by leo-from-spb** [comment]
Maxim, what's the problem?

**Comment by rez1dent3** [comment]
hello, does not connect to the database and no more errors. 
PS, username and password is correct. Using the cli client connects.

**Comment by rez1dent3** [comment]
The problem was solved by reinstalling the database Tools plugin.

--
ЗЫ, проблему решил удалив плагин DatabaseTools и установив его заново. Видимо в нем была проблема.

**Comment by tjlee** [comment]
It looks like it was incorrect dekaf lib version
